// Signed per-company tokens for /eod-entry — the form that renders inside
// GoHighLevel via a Custom Menu Link iframe. A CML URL is static, so the
// token is long-lived: HMAC(company slug, secret), no expiry. Revoke all
// links by rotating EOD_ENTRY_SECRET (falls back to WEBHOOK_SECRET so no new
// env var is strictly required). Links are generated by
// src/scripts/makeEodEntryLink.js in the repo root, which mirrors this HMAC.

import { createHmac, timingSafeEqual } from "node:crypto";

function secret(): string | null {
  return process.env.EOD_ENTRY_SECRET || process.env.WEBHOOK_SECRET || null;
}

function sign(slug: string, key: string): string {
  return createHmac("sha256", key).update(`eod-entry:${slug}`).digest("hex").slice(0, 32);
}

/** Token format: "<company-slug>.<hmac hex>". Returns the slug, or null if invalid. */
export function verifyEodEntryToken(token: string): string | null {
  const key = secret();
  if (!key) return null;
  const dot = token.lastIndexOf(".");
  if (dot <= 0) return null;
  const slug = token.slice(0, dot);
  const given = Buffer.from(token.slice(dot + 1));
  const expected = Buffer.from(sign(slug, key));
  if (given.length !== expected.length) return null;
  return timingSafeEqual(given, expected) ? slug : null;
}
